[package]
name = "learn_vulkano"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.32.3"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
winit = "0.27.3"
bytemuck = "1.16.0"
glam = {version = "0.27.0", features = ["bytemuck"]}